FROM node:18-alpine

WORKDIR /app

# Copier uniquement les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]

